### ISSUE TITLE
Add tictactoe to the homepage

### ISSUE THREAD

**Issue by Atema** [Bragi3000/Bragi3000#44]
To make the initial layout complete.

**Comment by nikolim** [comment]
@Atema whats the best way to access the songs stored in the application state?

**Comment by Atema** [comment]
When not using `connect`, `useSelector(state => selectSelectedSong(state, player)` (where `player` is one of the constants from `Constants/players.js`

**Comment by Atema** [comment]
And if you want to check if they're confirmed, use `selectSongIsConfirmed` instead of `selectSelectedSong`

**Comment by nikolim** [comment]
Great thank you!
