### ISSUE TITLE
Remove played songs from playlist

### ISSUE THREAD

**Issue by nikolim** [Bragi3000/Bragi3000#55]
Once song is played it should be removed from the playlist again

**Comment by Atema** [comment]
I'm not sure it should; it could just as well be kept so that it can be re-played later.

It can also be a bit difficult to manage removing played songs, because the website may not always know if songs are played (when the app's closed, for example)

**Comment by nikolim** [comment]
Ok good point. So we would keep them in them playlist but remove them from our view?

**Comment by Atema** [comment]
Something like that. Or show them grayed out based on the current song that's playing

**Comment by nikolim** [comment]
Done
