### ISSUE TITLE
Playlist only fetched when Playlist-Icon is pressed

### ISSUE THREAD

**Issue by nikolim** [Bragi3000/Bragi3000#78]
Move the fetching of the playlistID to make it when the app starts

**Comment by Atema** [comment]
@nikolim This could maybe be done in the `setSpotifyAuthData` action, so that the playlist is fetched every time the user logs in?

**Comment by nikolim** [comment]
Yes sounds good, and then also persist the playlistId and the banned songs to Firebase? Can we do this the same way as for the SpotifyAuth?
