### ISSUE TITLE
Firebase infinite loading

### ISSUE THREAD

**Issue by vanFrZy** [Bragi3000/Bragi3000#92]
On some devices there is an infinite waiting for firebase loading when accessing the page

**Comment by Atema** [comment]
I think I know what's happening, so will try to fix it tonight.

**Comment by nikolim** [comment]
Facing the same issue currently

**Comment by Atema** [comment]
As a workaround, you can disable the Firebase ready check in require authentication, I think

**Comment by nikolim** [comment]
Thanks, setting `firebaseReady: true` line 44 in src/Store/slices/auth.js works

**Comment by nikolim** [comment]
This let's me login into Bragi but not into Spotify

**Comment by nikolim** [comment]
I guess the problem is that fromFirebase is never called

**Comment by Atema** [comment]
Strange. Spotify login should work regardless of persistence

**Comment by Atema** [comment]
So disabling persistence altogether and then disabling the check for firebaseReady, things should still work, just the Spotify login will be gone on a refresh
